openapi: 3.0.3
info:
  title: CrewV CnR API
  description: |
    API for CrewV CnR - Player and crew management system
    
    This API allows you to:
    - Search for player information
    - Get API information and deployment region
  version: 1.0.0
  contact:
    name: CrewV CnR Support
  license:
    name: MIT

servers:
  - url: https://crewvapi.vercel.app
    description: Production server

paths:
  /:
    get:
      summary: API Information
      description: Returns general API information, including deployment region
      operationId: getApiInfo
      tags:
        - API Info
      responses:
        '200':
          description: API information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "CrewV CnR API"
                  description:
                    type: string
                    example: "Welcome!"
                  documentation:
                    type: string
                    example: "Coming soon"
                  version:
                    type: string
                    example: "1.0.0"
                  apiEndpoint:
                    type: string
                    example: "/"
                  region:
                    type: string
                    description: Name of the Vercel region where the API is deployed
                    example: "eu-west-1"
                  requestId:
                    type: string
                    description: Unique request identifier
                    example: "8e8244c6b43f"
                  timestamp:
                    type: string
                    format: date-time
                    description: ISO 8601 timestamp of the response
                    example: "2025-09-13T10:30:00.000Z"
                required:
                  - name
                  - description
                  - documentation
                  - version
                  - apiEndpoint
                  - region
                  - requestId
                  - timestamp

  /players/info:
    get:
      summary: Search Player Information
      description: |
        Search for a player by ID, UID, or username.
        At least one parameter must be provided.
      operationId: getPlayerInfo
      tags:
        - Players
      parameters:
        - name: Accept
          in: header
          description: Content type
          required: true
          schema:
            type: string
            default: application/json
            enum:
              - application/json
        - name: id
          in: query
          description: Numeric ID of the player in the database
          required: false
          schema:
            type: integer
            minimum: 1
          example: 24386
        - name: uid
          in: query
          description: Unique UID of the player
          required: false
          schema:
            type: string
          example: "072D51B8FA964658AE9BBCA0B7766FA9"
        - name: username
          in: query
          description: Exact Username of the player (with crew Tag)
          required: false
          schema:
            type: string
          example: "[CBŚP] Baldy"
      responses:
        '200':
          description: Player information found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Unique player ID
                      example: 32689
                    Uid:
                      type: string
                      description: Unique player UID
                      example: "072D51B8FA964658AE9BBCA0B7766FA9"
                    Username:
                      type: string
                      description: Player username
                      example: "[CBŚP] Baldy"
                    Crew:
                      type: string
                      nullable: true
                      description: Player's crew (can be null)
                      example: "CBŚP"
                    LastSeen:
                      type: string
                      format: date-time
                      description: Last time the player was seen
                      example: "2025-09-12T23:10:28.430Z"
                    createdAt:
                      type: string
                      format: date-time
                      description: When the player record was created
                      example: "2025-09-13T00:02:05.723Z"

                  required:
                    - id
                    - Uid
                    - Username
        '400':
          description: Missing or invalid query parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Please specify either 'id' or 'uid' or 'username' for the search."
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error."

components:
  schemas:
    ApiInfo:
      type: object
      description: General API information
      properties:
        name:
          type: string
          description: API name
        description:
          type: string
          description: API description
        documentation:
          type: string
          description: Documentation status
        version:
          type: string
          description: API version
        apiEndpoint:
          type: string
          description: Main API endpoint
        region:
          type: string
          description: Deployment region
        requestId:
          type: string
          description: Request identifier
        timestamp:
          type: string
          format: date-time
          description: Response timestamp

    Player:
      type: object
      description: Player information
      properties:
        id:
          type: integer
          description: Unique numeric identifier
        Uid:
          type: string
          description: Unique player UID
        Username:
          type: string
          description: Username
        Crew:
          type: string
          nullable: true
          description: Player's crew
        LastSeen:
          type: string
          format: date-time
          description: Last time the player was seen
        createdAt:
          type: string
          format: date-time
          description: When the player record was created

    ErrorResponse:
      type: object
      description: Standard error response
      properties:
        error:
          type: string
          description: Error message
        message:
          type: string
          description: Informational message (optional)

tags:
  - name: API Info
    description: General API information
  - name: Players
    description: Player management and search

externalDocs:
  description: Complete documentation (coming soon)
  url: https://gitbook.com/crewv